### ISSUE TITLE
Videos Not Playable

### ISSUE THREAD

**Issue by shardulsrivastava** [arush-sal/linuxacademy-dl#2]
Hi @arush-sal  even your code has the same problem. The videos are not playable

**Comment by arush-sal** [comment]
@shardulsrivastava Can you share the exact steps you took? Along with the output of these:
`python -V`
`ffmpeg -version|head -n 1`

**Comment by shardulsrivastava** [comment]
Please find the Details below 
FFMPEG Version 
C:\Users\SHARDULS>ffmpeg -v
ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)

Python Version 

C:\Users\SHARDULS>python -V
Python 2.7.13

Steps 
Note : Python and ffmpeg is in PATH
1)Cloned your repo : git clone https://github.com/arush-sal/linuxacademy-dl/
2) Open CMD with Administrator and go to clone repository
3) cd C:\Users\SHARDULS\linuxacademy-dl\linuxacademy_dl
4) Run the command : 
python __main__.py -u <username> -p <password> https://linuxacademy.com/cp/modules/view/id/11

**Comment by shardulsrivastava** [comment]
Now All the videos are downloaded but not playable. Is there a way to repair them using ffmpeg ????

**Comment by arush-sal** [comment]
@shardulsrivastava I'll try to recreate the issue in Windows and get back to you.

p.s: None way that I know can be used to repair those videos

**Comment by shardulsrivastava** [comment]
Btw whats the recommended version of ffmpeg ??

**Comment by arush-sal** [comment]
I am using v2.8.10 of ffmpeg and python v2.7.12 on Ubuntu machine

p.s: If you can share your email address we can resolve the issue faster

**Comment by shardulsrivastava** [comment]
Please use shardul.srivastav007@gmail.com to communicate for the issue.

**Comment by arush-sal** [comment]
It says wrong email address

**Comment by shardulsrivastava** [comment]
Oops.. sorry its shardul.srivastava007@gmail.com
