### ISSUE TITLE
No Such file or directory found

### ISSUE THREAD

**Issue by jlwils28** [arush-sal/linuxacademy-dl#3]
When I try to run the "docker run -it -v <local-dir>:/media arush/linuxacademy-dl" command I get the error message 'bash: local-dir: No such file or directory' Then if i replace '<local-dir>' with an actual directory I get this message 'bash: :/media: No such file or directory'

**Comment by arush-sal** [comment]
@jlwils28 `docker run -it -v <local media>:/media arush/linuxacademy-dl`

where <local media> should be a local directory path.

[Read more](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume)

**Comment by jlwils28** [comment]
I'm sorry I don't understand your question? The videos I download from Linux Academy still don't play. I'm on a Linux machine btw

**Comment by arush-sal** [comment]
@jlwils28 Just run 
`docker run -it -v /mnt:/media arush/linuxacademy-dl` and then use the command line to download the videos. I just tested it and it's working perfectly.

**Comment by jlwils28** [comment]
Cool I will try it in a few hours and tell you the results

**Comment by jlwils28** [comment]
That worked perfectly. Thanks for all of the help

**Comment by arush-sal** [comment]
closing the issue.
